global using System.ComponentModel.DataAnnotations;
global using System.Threading.RateLimiting;
global using Api.Configuration;
global using Api.Endpoints;
global using Api.Logging;
global using Api.Middleware;
global using Api.Dtos;
global using Api.Services;
global using Microsoft.AspNetCore.Diagnostics.HealthChecks;
global using Microsoft.Extensions.Diagnostics.HealthChecks;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.AspNetCore.RateLimiting;
global using Microsoft.Extensions.DependencyInjection;
global using Serilog;
global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using SerilogLogger = Serilog.ILogger;
